version: '2'
services:
  php:
    build:
      context: ./php
    depends_on:
      - db
    volumes:
      - "./eccube-3.0.15:/var/www"
    ports:
      - "80:80"
  db:
    build:
      context: ./db
    volumes:
      - "db-volume:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ROOTPW
      MYSQL_USER: test
      MYSQL_PASSWORD: TESTPW
      MYSQL_DATABASE: eccube_test
    ports:
      - "3306:3306"
volumes:
  db-volume:
